# Generated by Django 6.0.7 on 2026-07-28 15:09

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar ($)'), ('EUR', 'Euro (€)'), ('GBP', 'British Pound (£)'), ('INR', 'Indian Rupee (₹)'), ('THB', 'Thai Baht (฿)'), ('JPY', 'Japanese Yen (¥)'), ('AUD', 'Australian Dollar (A$)'), ('CAD', 'Canadian Dollar (C$)'), ('CNY', 'Chinese Yuan (¥)'), ('SGD', 'Singapore Dollar (S$)'), ('AED', 'UAE Dirham (د.إ)'), ('CUSTOM', 'Custom symbol / upload own icon')], default='USD', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='custom_currency_icon',
            field=models.ImageField(blank=True, help_text="Optional small icon/logo to use as the currency symbol instead of text (only used when Currency is 'Custom').", null=True, upload_to=stores.models.currency_icon_path),
        ),
        migrations.AddField(
            model_name='store',
            name='custom_currency_symbol',
            field=models.CharField(blank=True, help_text="Only used when Currency is set to 'Custom' -- e.g. 'Kč', '₪', 'R$'.", max_length=8),
        ),
    ]
