# Generated by Django 6.0.7 on 2026-08-03 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_store_currency_code_store_custom_currency_icon_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='address',
        ),
        migrations.RemoveField(
            model_name='store',
            name='phone_number',
        ),
        migrations.AddField(
            model_name='fooditem',
            name='pincode',
            field=models.CharField(default=121991, help_text='Required. Customers can search for stores by pincode.', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fooditem',
            name='store_category',
            field=models.CharField(choices=[('FOOD', 'Food & Beverage'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion & Apparel'), ('GROCERY', 'Grocery & Daily Needs'), ('HEALTH', 'Health & Beauty'), ('HOME', 'Home & Living'), ('SPORTS', 'Sports & Fitness'), ('BOOKS', 'Books & Stationery'), ('TOYS', 'Toys & Games'), ('AUTOMOTIVE', 'Automotive'), ('OTHER', 'Other')], default='FOOD', help_text='What kind of store is this? Customers can filter by this on the main page.', max_length=20),
        ),
        migrations.AddField(
            model_name='store',
            name='pincode',
            field=models.CharField(default='', help_text='Required. Customers can search for your store by pincode.', max_length=10),
        ),
        migrations.AddField(
            model_name='store',
            name='store_category',
            field=models.CharField(choices=[('FOOD', 'Food & Beverage'), ('ELECTRONICS', 'Electronics'), ('FASHION', 'Fashion & Apparel'), ('GROCERY', 'Grocery & Daily Needs'), ('HEALTH', 'Health & Beauty'), ('HOME', 'Home & Living'), ('SPORTS', 'Sports & Fitness'), ('BOOKS', 'Books & Stationery'), ('TOYS', 'Toys & Games'), ('AUTOMOTIVE', 'Automotive'), ('OTHER', 'Other')], default='FOOD', help_text='What kind of store is this? Customers can filter by this on the main page.', max_length=20),
        ),
    ]
