# Generated by Django 6.0.8 on 2026-08-27 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Tax % for this item (e.g. 7.00 for 7%). Set to 0 if price is final (no tax).', max_digits=5),
        ),
        migrations.AddField(
            model_name='store',
            name='address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='store',
            name='phone_number',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='store',
            name='require_customer_address',
            field=models.BooleanField(default=False, help_text="Ask for the customer's address at checkout."),
        ),
        migrations.AddField(
            model_name='store',
            name='require_customer_name',
            field=models.BooleanField(default=False, help_text="Ask for the customer's name at checkout."),
        ),
    ]
