# Generated by Django 6.0.7 on 2026-08-28 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_fooditem_tax_percentage_store_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='accept_orders_when_closed',
            field=models.BooleanField(default=False, help_text='If enabled, customers can place orders even when your store is closed.'),
        ),
        migrations.AddField(
            model_name='store',
            name='timezone',
            field=models.CharField(default='UTC', help_text='Select your country/timezone so operating hours match your local time.', max_length=50),
        ),
    ]
