# Generated by Django 6.0.7 on 2026-08-31 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_fooditem_item_code_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='fooditem',
            name='min_stock_quantity',
            field=models.PositiveIntegerField(default=10, help_text='Alert when stock falls below this number.'),
        ),
    ]
