# Generated by Django 6.0.8 on 2026-09-11 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_fooditem_min_stock_quantity'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'name')},
        ),
        migrations.AddField(
            model_name='category',
            name='name_en',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_th',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='category',
            name='name_zh_hans',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='name_th',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='fooditem',
            name='name_zh_hans',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_th',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='message_zh_hans',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_en',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_th',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='title_zh_hans',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_th',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='description_zh_hans',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('store', 'name'), ('store', 'name_en'), ('store', 'name_th'), ('store', 'name_zh_hans')},
        ),
    ]
