# Generated by Django 6.0.8 on 2026-09-11 17:44

import stores.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_category_unique_together_category_name_en_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fooditem',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='fooditem',
            name='store_category',
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='message',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='contactmessage',
            name='name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='min_stock_quantity',
            field=models.PositiveIntegerField(default=10),
        ),
        migrations.AlterField(
            model_name='fooditem',
            name='tax_percentage',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='operatinghours',
            name='is_closed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='custom_currency_icon',
            field=models.ImageField(blank=True, help_text='Optional small icon/logo to use as currency symbol.', null=True, upload_to=stores.models.currency_icon_path),
        ),
        migrations.AlterField(
            model_name='store',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='require_customer_address',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='store',
            name='require_customer_name',
            field=models.BooleanField(default=False),
        ),
    ]
