# Generated by Django 6.0.8 on 2026-09-13 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_remove_fooditem_pincode_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TranslationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original_text', models.CharField(db_index=True, max_length=255)),
                ('language_code', models.CharField(db_index=True, max_length=10)),
                ('translated_text', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Translation Master',
                'verbose_name_plural': 'Translation Master Records',
                'unique_together': {('original_text', 'language_code')},
            },
        ),
    ]
